menu:
- {name: 'Research', url: '#research'}
- {name: 'Team', url: '#team'}
- {name: 'Publications', url: '#publications'}
- {name: 'Contact', url: '#contact'}

people:
# - {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}

courses:
# - {name: 'Vector Calculus', url: 'vector-calculus'}

social:
# - {icon: 'github', link: 'https://github.com/nbellive'}

contacts:
- {name: 'Dr. Nathan M. Belliveau', title: 'Assistant Professor', department: 'Department of Biochemistry and BioFrontiers Institute', institution: 'University of Colorado Boulder', institution_address: 'Jennie Smoly Caruthers Biotechnology Building (JSCBB)', email: 'nathan.belliveau @ colorado.edu', email_link: 'nathan.belliveau@colorado.edu', office: 'JSCBB A320', lab: 'JSCBB A354, A368', image: 'assets/img/contact.jpg'}
